Update __init__.py
comment asyncio, because it has bug when we use Fast API Uvicorn. 

ValueError: Can't patch loop of type <class 'uvloop.Loop'>

/site-packages/pyrdf2vec/__init__.py", line 6, in <module>